<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StoreApp.Application\StoreApp.Application.csproj" />
    <ProjectReference Include="..\StoreApp.Domain\StoreApp.Domain.csproj" />
  </ItemGroup>
</Project>
